workflows:
  ios-workflow:
    name: iOS Build & Upload
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build .ipa
        script: flutter build ipa --release --build-name=3.1.0 --build-number=29
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth:
          integration: ios-upload
          type: api_key
          apple_id: dorayagi@gmail.com
          api_key_id: WJBX749WAD
          issuer_id: 3cdd00be-36f5-4047-a99e-439c53b66d13
          api_private_key: |
            -----BEGIN PRIVATE KEY-----
            MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDq32loCMN1jwqE9K
            qXUOoH/e4sKcNDp9HBVnE+LjdzqgCgYIKoZIzj0DAQehRANCAASTJjgh1ih6AKCH
            TegvwSQnEx3u0KyaerLPKpGmfOmsEqyBxaXLzKo14MT8Sd8FhFDC7w8Wpc48Z+yS
            7sxN2Ya6
            -----END PRIVATE KEY-----
